export const OAUTH_GOOGLE_ID = 'OAUTH_GOOGLE_ID';
export const OAUTH_GOOGLE_SECRET = 'OAUTH_GOOGLE_SECRET';
export const OAUTH_GOOGLE_CALLBACK = 'OAUTH_GOOGLE_CALLBACK';

export const JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET';
export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
export const JWT_ACCESS_TOKEN_EXPIRATION_TIME = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME';
export const JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME';

export const NODE_ENV = 'NODE_ENV';
export const DATABASE_HOST = 'DATABASE_HOST';
export const DATABASE_PORT ='DATABASE_PORT';
export const DATABASE_USERNAME = 'DATABASE_USERNAME';
export const DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const DATABASE_TEST_SCHEMA = 'DATABASE_TEST_SCHEMA';
export const DATABASE_SCHEMA = 'DATABASE_SCHEMA';
export const DATABASE_SYNCHRONIZE = 'DATABASE_SYNCHRONIZE';