export const BOOKMARKS_REPOSITORY = 'BOOKMARKS_REPOSITORY';
export const COMMENTS_REPOSITORY = 'COMMENTS_REPOSITORY';
export const COMMENT_LIKES_REPOSITORY = 'COMMENT_LIKES_REPOSITORY';
export const QUESTIONS_REPOSITORY = 'QUESTIONS_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';

export const QUESTIONS_QUERY_REPOSITORY = 'QUESTIONS_QUERY_REPOSITORY';
