import { QuestionEntity } from "src/questions/infrastructure/entity/question.entity";
import { UserEntity } from "src/users/infrastructure/entity/user.entity";
import { DataSource } from "typeorm";
import { Seeder } from "typeorm-extension";

const user = new UserEntity();
user.id = 1;

export default class DummyDataSeeder implements Seeder {
  async run(dataSource: DataSource): Promise<any> {
    const repository = dataSource.getRepository(QuestionEntity);
    await repository.insert([
      { title: 'test1', content: 'test content..1', user },
      { title: 'test2', content: 'test content..1', user },
      { title: 'test3', content: 'test content..1', user },
      { title: 'test4', content: 'test content..1', user },
      { title: 'test5', content: 'test content..1', user },
      { title: 'test6', content: 'test content..1', user },
      { title: 'test7', content: 'test content..1', user },
      { title: 'test8', content: 'test content..1', user },
      { title: 'test9', content: 'test content..1', user },
      { title: 'test10', content: 'test content..1', user },
      { title: 'test11', content: 'test content..1', user },
      { title: 'test12', content: 'test content..1', user },
      { title: 'test13', content: 'test content..1', user },
      { title: 'test14', content: 'test content..1', user },
      { title: 'test15', content: 'test content..1', user },
      { title: 'test16', content: 'test content..1', user },
      { title: 'test17', content: 'test content..1', user },
      { title: 'test18', content: 'test content..1', user },
      { title: 'test19', content: 'test content..1', user },
      { title: 'test20', content: 'test content..1', user },
      { title: 'test21', content: 'test content..1', user },
      { title: 'test22', content: 'test content..1', user },
      { title: 'test23', content: 'test content..1', user },
      { title: 'test24', content: 'test content..1', user },
      { title: 'test25', content: 'test content..1', user },
      { title: 'test26', content: 'test content..1', user },
      { title: 'test27', content: 'test content..1', user },
      { title: 'test28', content: 'test content..1', user },
      { title: 'test29', content: 'test content..1', user },
      { title: 'test30', content: 'test content..1', user },
      { title: 'test31', content: 'test content..1', user },
      { title: 'test32', content: 'test content..1', user },
      { title: 'test33', content: 'test content..1', user },
      { title: 'test34', content: 'test content..1', user },
      { title: 'test35', content: 'test content..1', user },
      { title: 'test36', content: 'test content..1', user },
      { title: 'test37', content: 'test content..1', user },
      { title: 'test38', content: 'test content..1', user },
      { title: 'test39', content: 'test content..1', user },
      { title: 'test40', content: 'test content..1', user },
      { title: 'test41', content: 'test content..1', user },
      { title: 'test42', content: 'test content..1', user },
      { title: 'test43', content: 'test content..1', user },
      { title: 'test44', content: 'test content..1', user },
      { title: 'test45', content: 'test content..1', user },
      { title: 'test46', content: 'test content..1', user },
      { title: 'test47', content: 'test content..1', user },
      { title: 'test48', content: 'test content..1', user },
      { title: 'test49', content: 'test content..1', user },
      { title: 'test50', content: 'test content..1', user },
      { title: 'test51', content: 'test content..1', user },
      { title: 'test52', content: 'test content..1', user },
      { title: 'test53', content: 'test content..1', user },
      { title: 'test54', content: 'test content..1', user },
      { title: 'test55', content: 'test content..1', user },
      { title: 'test56', content: 'test content..1', user },
      { title: 'test57', content: 'test content..1', user },
      { title: 'test58', content: 'test content..1', user },
      { title: 'test59', content: 'test content..1', user },
      { title: 'test60', content: 'test content..1', user },
      { title: 'test61', content: 'test content..1', user },
      { title: 'test62', content: 'test content..1', user },
      { title: 'test63', content: 'test content..1', user },
      { title: 'test64', content: 'test content..1', user },
      { title: 'test65', content: 'test content..1', user },
      { title: 'test66', content: 'test content..1', user },
      { title: 'test67', content: 'test content..1', user },
      { title: 'test68', content: 'test content..1', user },
      { title: 'test69', content: 'test content..1', user },
      { title: 'test70', content: 'test content..1', user },
      { title: 'test71', content: 'test content..1', user },
      { title: 'test72', content: 'test content..1', user },
      { title: 'test73', content: 'test content..1', user },
      { title: 'test74', content: 'test content..1', user },
      { title: 'test75', content: 'test content..1', user },
      { title: 'test76', content: 'test content..1', user },
      { title: 'test77', content: 'test content..1', user },
      { title: 'test78', content: 'test content..1', user },
      { title: 'test79', content: 'test content..1', user },
      { title: 'test80', content: 'test content..1', user },
      { title: 'test81', content: 'test content..1', user },
      { title: 'test82', content: 'test content..1', user },
      { title: 'test83', content: 'test content..1', user },
      { title: 'test84', content: 'test content..1', user },
      { title: 'test85', content: 'test content..1', user },
      { title: 'test86', content: 'test content..1', user },
      { title: 'test87', content: 'test content..1', user },
      { title: 'test88', content: 'test content..1', user },
      { title: 'test89', content: 'test content..1', user },
      { title: 'test90', content: 'test content..1', user },
      { title: 'test91', content: 'test content..1', user },
      { title: 'test92', content: 'test content..1', user },
      { title: 'test93', content: 'test content..1', user },
      { title: 'test94', content: 'test content..1', user },
      { title: 'test95', content: 'test content..1', user },
      { title: 'test96', content: 'test content..1', user },
      { title: 'test97', content: 'test content..1', user },
      { title: 'test98', content: 'test content..1', user },
      { title: 'test99', content: 'test content..1', user },
      { title: 'test100', content: 'test content..1', user },
    ])
  } 
}